[package]
name = "bot"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cimi = { workspace = true }
lark = { workspace = true }
wechat = { workspace = true }

bytes = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }

clap = { version = "4.6.6", features = ["derive"] }
dotenvy = "0.15.7"
logforth = { version = "0.30.1", features = ["starter-log"] }
